name: english_center
description: English Center Mobile App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  path_provider: ^2.0.9
  flutter_easyloading: ^3.0.3
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.10
  file_picker: ^4.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.2
  circle_nav_bar: ^1.0.2
  flutter_svg: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  table_calendar: ^3.0.5
  google_sign_in: ^5.3.0
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^5.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - images/GB.svg
    - images/VN.svg
    - images/Toeic.jpg
    - images/Ielts.png
    - images/logo.png
  generate: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
